FROM node:16
WORKDIR /workspace
# Copy package.json and package-lock.json to the working directory
COPY package*.json ./
# Install project dependencies
RUN npm install
COPY . .
# Build the Next.js application
RUN npm run build
EXPOSE 3000
CMD  "npm run dev"