global:
  scrape_interval:     5s
  scrape_timeout:      5s
scrape_configs:
  - job_name: torchserve
    scrape_interval: 5s
    scrape_timeout: 5s
    metrics_path: /metrics
    static_configs:
      - targets: 
        - ctorchserve:8082 #monitor torchserve container

  - job_name: prometheus
    honor_timestamps: true
    scrape_interval: 5s
    scrape_timeout: 5s
    metrics_path: /metrics
    scheme: http
    static_configs:
    - targets:
      - localhost:9090